refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout

loggers:
  ct::ws_connector::deribit_ws:
    level: info
    appenders:
      - requests
      - stdout
    additive: false